### ISSUE TITLE
Broken 'preview' link in README

### ISSUE THREAD

**Issue by anshulxyz** [idbrii/vim-sandydune#2]
<img width="436" alt="Screenshot 2024-07-28 at 12 25 24 AM" src="https://github.com/user-attachments/assets/8d44b2f9-f302-402e-b493-154e356322cb">

The link to the preview of the colorscheme, which links to https://vimcolors.com/209/sandydune/dark is broken. I believe the owners of the https://vimcolors.com/ have changed and now the side has become some SEO-centric-generic-coding-blog-post-slop.

I suggest an alternative, https://vimcolorschemes.com/idbrii/vim-sandydune

BTW loved your colorscheme and have been using it. Thank you for the work on it.

**Comment by idbrii** [comment]
Thanks for pointing that out! Glad you like the colorscheme.
